spring:
  kafka:
    bootstrap-servers:
      - localhost:29092
    consumer:
      client-id: my-client-consumer
      group-id: spring-application-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.drdonna.EXAMPLE.REPLACE.controllers.events.converters.MessageDeSerializer
    producer:
      client-id: my-client-application
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.drdonna.EXAMPLE.REPLACE.controllers.events.converters.MessageSerializer

topic:
  name: "transaction.000"
server:
  port: 9191